---
title: "OLC 750 - R Yazılımına Giriş"
output: html_document
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
# remotes::install_github("mitchelloharawild/icons")
# devtools::install_github("ropenscilabs/icon")
# https://www.r-bloggers.com/2018/05/icon-web-icons-for-rmarkdown/

# Search icons: https://fontawesome.com/v5.15/icons
library("fontawesome")

#Setup knitr
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, warning = FALSE, background = "gray85",
                      message = FALSE, fig.width=8, fig.height=6, comment = NA,
                      fig.align = 'center')
```


<br>
<center>
</center>
<br>
<br>

## Ders Hakkında

Bu dersin amacı, R yazılımını kullanarak veri üzerinde istenilen istatistiksel ve psikometrik işlemlerin yapılabilmesini sağlamaktır. Tez ve makale çalışmalarında öğrencilerimizin R Programı ile birçok analizleri kendi başlarına yapmalarını sağlamaktır. 
(İzlence) [**İzlence**](OLC750_Izlence.html).

<br>

## Eğitmen

`r fontawesome::fa("user-tie", fill = "black")` [Dr. Kübra Atalay Kabasakal](https://avesis.hacettepe.edu.tr/katalay)


`r fontawesome::fa("envelope", fill = "black")` <kkatalay@gmail.com>

<br>

## Kitaplar

-  Atar, B., Atalay Kabasakal, K, Unsal Ozberk, E. B., Ozberk, E. H. & Kibrislioglu Uysal, N. (2020). R ile Veri Analizi ve Psikometri Uygulamaları, Pegem Akademi, Ankara.

- Desjardins, C. D., & Bulut, O. (2018). [Handbook of educational measurement and psychometrics using R](https://www.routledge.com/Handbook-of-Educational-Measurement-and-Psychometrics-Using-R/Desjardins-Bulut/p/book/9780367734671). Boca Raton, FL: CRC Press.



<br>

## Ders Metaryelleri

- Ders notları ve okumalar  [moodle](https://lisansustu.hacettepe.edu.tr/login/index.php). 

- Dönem boyunca [R](https://cran.r-project.org/) ve [RStudio](https://www.rstudio.com/) kullanacağız. 


<br>



